### ISSUE TITLE
Unexpected reserved word

### ISSUE THREAD

**Issue by cryptonobo** [lukeliasi/binance-dca-bot#11] opened 2021-09-01 00:44 UTC
await runBot();
^^^^^

SyntaxError: Unexpected reserved word

    at Loader.moduleStrategy (internal/modules/esm/translators.js:88:18)
    at async link (internal/modules/esm/module_job.js:41:21)

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-dca-bot@1.0.0 start: `node ./src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the binance-dca-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/linux/.npm/_logs/2021-09-01T00_38_33_541Z-debug.log
```

my log 

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/linux/.nvm/versions/node/v14.4.0/bin/node',
1 verbose cli   '/home/linux/.nvm/versions/node/v14.4.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle binance-dca-bot@1.0.0~prestart: binance-dca-bot@1.0.0
6 info lifecycle binance-dca-bot@1.0.0~start: binance-dca-bot@1.0.0
7 verbose lifecycle binance-dca-bot@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle binance-dca-bot@1.0.0~start: PATH: /home/linux/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/linux/binance-dca-bot/node_modules/.bin:/home/linux/.nvm/versions/node/v14.4.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle binance-dca-bot@1.0.0~start: CWD: /home/linux/binance-dca-bot
10 silly lifecycle binance-dca-bot@1.0.0~start: Args: [ '-c', 'node ./src/index.js' ]
11 silly lifecycle binance-dca-bot@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle binance-dca-bot@1.0.0~start: Failed to exec start script
13 verbose stack Error: binance-dca-bot@1.0.0 start: `node ./src/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/linux/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/linux/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid binance-dca-bot@1.0.0
15 verbose cwd /home/linux/binance-dca-bot
16 verbose Linux 5.11.0-27-generic
17 verbose argv "/home/linux/.nvm/versions/node/v14.4.0/bin/node" "/home/linux/.nvm/versions/node/v14.4.0/bin/npm" "run" "start"
18 verbose node v14.4.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error binance-dca-bot@1.0.0 start: `node ./src/index.js`
22 error Exit status 1
23 error Failed at the binance-dca-bot@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Could   you help me ? 
Thanks

**Comment by lukeliasi** [comment] 2021-09-01 09:06
Duplicate of issue #6

**Closed** 2021-09-01 09:06 UTC
Labels: duplicate

**Comment by cryptonobo** [comment] 2021-09-01 13:45
you close it but its not exactly the same issue .... i have v14.4.0 installed ... any suggestion ?

**Comment by lukeliasi** [comment] 2021-09-01 13:59
> you close it but its not exactly the same issue .... i have v14.4.0 installed ... any suggestion ?

Sorry it seems that node version is not compatible either. I will look into transpiling into es5 so older versions of node work. In the meantime please try v14.17.6 and that should work.

**Comment by cryptonobo** [comment] 2021-09-01 14:53
Working with v14.17.6 !! Thanks
